### ISSUE TITLE
Unable to rename file adding the .yml to the end on Windows

### ISSUE THREAD

**Issue by predatorian3** [Netflix-Skunkworks/go-jira#44] opened 2016-06-30 02:14 UTC
Attempting to create a Jira task, I run into the following error when executing `jira create -i Request`

```
C:\Users\user01
λ jira login
Enter Password for user01:

C:\Users\user01
λ jira issuetypes
Request:
Incident:
Sub-task:     The sub-task of the issue
Project:
Epic:         Created by JIRA Agile - do not edit or delete. Issue type for a big user story that needs to be broken down.
Task:         A task that needs to be done.

C:\Users\user01
λ jira create -i Task
2016-06-29T20:51:18.200-05:00 ERROR [cli.go:268] Failed to rename C:\Users\user01\.jira.d\tmp\create-task-063183995 to C:\Users\user01\.jira.d\tmp\create-task-063183995.yml: 
  rename C:\Users\user01\.jira.d\tmp\create-task-063183995 C:\Users\user01\.jira.d\tmp\create-task-063183995.yml: 
  The process cannot access the file because it is being used by another process.
2016-06-29T20:51:18.225-05:00 ERROR [main.go:455] rename C:\Users\user01\.jira.d\tmp\create-task-063183995 C:\Users\user01\.jira.d\tmp\create-task-063183995.yml: 
  The process cannot access the file because it is being used by another process.
```

I believe this is related to a GO function os.Rename() that has had some debate about functioning on Windows and POSIX systems. 
* https://github.com/golang/go/issues/3366
* https://golang.org/pkg/os/#Rename

Here are the links to the Code Line Numbers from the errors. The main.go error is just the error check, and I linked the create case statement. 
* https://github.com/Netflix-Skunkworks/go-jira/blob/master/cli.go#L267
* https://github.com/Netflix-Skunkworks/go-jira/blob/master/main/main.go#L345

Once again though, still working on the learning GO thing, so hopefully I can pitch in soon.

**Comment by coryb** [comment] 2016-06-30 05:57
Thanks for the report.  Interesting.  I don't think this has to do with issue you linked to, at least we are not trying to overwrite a file that already exists.  

I think the problem is that go-jira has a tmp file open, then tries to rename that file, which apparently seems to be forbidden on windows resulting in:
```
The process cannot access the file because it is being used by another process
```

The  goal of the code is to create a tmp file with a known file extension (ie .yml) that will tell editors to use yaml editing mode, the Go TempFile routine does not let you specify the file extension.   So we create the file (which also opens it) then try to rename the file while still open.

I think the "work around" would be to just close the file, move it, then reopen it.

**Comment by coryb** [comment] 2016-06-30 06:21
I have published a new release with my work around, which seems to work with my limited testing . Please try it out, downloads here: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v0.1.2

**Comment by predatorian3** [comment] 2016-06-30 13:39
Cool, this is working now, just need to figure out the fields bit in the YAML, seems some fields in our Jira instance are uneditable.

**Comment by coryb** [comment] 2016-06-30 15:59
Yeah, the fields are fussy because Jira allows so much customization.  `reporter` is commonly not allowed to be updated, and the others likely depend on the customizations to your project type and issue type.  The error messages after posting the issue to Jira should tell you what fields are not allowed.  When you figure out what works then you can modify the template and put it in `%USERPROFILE%\.jira.d\templates\create.yml` so then go-jira will use that template in the future.

**Comment by coryb** [comment] 2016-06-30 15:59
closing this issue.

**Closed by coryb** 2016-06-30 15:59 UTC
